### ISSUE TITLE
Adicionar sessão "Apoio" na página de patrocinadores

### ISSUE THREAD

**Issue by nawarian** [PHPeste/phpeste.github.io#18]
![sebrae-logo-1](https://user-images.githubusercontent.com/3905582/189930627-323f1b70-c22b-4515-91f0-5e7690b49ffe.png)
![sebraelab](https://user-images.githubusercontent.com/3905582/189930639-b9b8f3c9-a4a2-4cf4-828e-781ff6e9fa27.png)

**Comment by allythy** [comment]
Depois da sessão bronze cria uma área como no titulo apoio e adicionar as duas logos. O nome "Seja um patrocinador" deixa depois da sessão de apoio.
![aaaa](https://user-images.githubusercontent.com/21327808/189951592-5474aad0-73dc-4771-9b1d-db5416206492.png)
