### ISSUE TITLE
Adicionar organização do PHPeste na página "Sobre"

### ISSUE THREAD

**Issue by nawarian** [PHPeste/phpeste.github.io#20]
Página: https://www.phpeste.org/about/

Adicionar um card para cada pessoa participando da organização.

Para cada pessoa adicionar:
* Nome completo
* Github / Twitter / LinkedIn (o que a pessoa quiser mostrar)
* Website
* Foto
* Bio (<3 parágrafos)

**Comment by nawarian** [comment]
Nome completo: Níckolas Da Silva (nawarian)
Github: https://github.com/nawarian
Twitter: https://twitter.com/nawarian
LinkedIn: https://www.linkedin.com/in/nawarian/
Website: https://codamos.com.br
Foto: 
![nickolas-da-silva](https://user-images.githubusercontent.com/3905582/189954725-fedb6e9c-38b4-4a8c-939a-481d31b8adcb.jpg)

Bio:

> Desenvolvedor PHP há 10 anos e gerente, mora em Berlim na Alemanha e trabalha na rede social ResearchGate.

> Também é co-organizador da comunidade PHPSP, do podcast [PodEntender](https://podentender.com.br) e autor do site [Codamos](https://codamos.com.br).

**Comment by julianaabs** [comment]
**Nome completo:** Juliana Barbosa dos Santos
**Github:** https://github.com/julianaabs
**Linkedin:** https://www.linkedin.com/in/juliana-barbosa-dos-santos-11085514a/
**Foto:**
![avatar62040919](https://user-images.githubusercontent.com/14303877/189959862-89f247bb-1f13-4649-b982-c22cc4136528.jpg)
**Bio:**
`Desenvolvedora PHP há 4 anos, trabalha há 5 anos com desenvolvimento. Mora em Natal-RN trabalha na OLX Brasil.`
`Participa das comunidades PHP-RN e PHP Women BR`

**Comment by allythy** [comment]
Nome completo: Allythy
Github: https://github.com/allythy
LinkedIn: https://www.linkedin.com/in/allythy/
Website: https://allythy.github.io/
Foto: Podei manter a atual
Bio: Entusiasta do movimento de Software Livre, coordenador da [PotiLivre](https://www.potilivre.org/) (Comunidade Potiguar de Software Livre). Fundador e coordenador do PHP-RN, coordenador do [GruPy-RN](https://meetup.grupyrn.org/) e desenvolvedor.

**Comment by itepifanio** [comment]
Nome completo: Ítalo Epifânio de Lima e Silva (itepifanio)
Github: https://github.com/itepifanio
Twitter: https://twitter.com/itepifanio
LinkedIn: https://www.linkedin.com/in/italoepifanio/
Website: https://itepifanio.github.io

![20220420_224901](https://user-images.githubusercontent.com/6730205/189961179-081d54e7-3977-4157-b2f1-24bf0d0b6050.jpg)

Bio: Pesquisador e desenvolvedor na Palaimon GmbH. Estudante de ciência da computação na UFRN. Participa das comunidades PHP-RN e Grupy RN. Garimpeiro de bandas e jogador de basquete nas horas vagas.

**Comment by jeanjar** [comment]
Github: https://github.com/jeanjar
Twitter: https://twitter.com/jean_jar
LinkedIn: https://www.linkedin.com/in/jeanjar
Website: https://jeanjar.github.io/

![image](https://user-images.githubusercontent.com/6249816/189969292-42d2e117-048e-4385-bdf9-bb74bfa72a64.png)

Bio: Pai de Olívia, Analista de sistemas formado no IFRN, mestre pela UFRN, desenvolvedor PHP a mais de 10 anos, adora repassar conhecimento e aprender coisas novas. Participa da comunidade PHP-RN.
